syntax = "proto3";
package api;
option java_package = "br.ufrn.dimap.api.grpc";
option java_multiple_files = true;

service GatewayService {
  rpc pulse(HeartbeatRequest) returns (HeartbeatResponse);
  rpc subscriber(SubscribeRequest) returns (SubscribeResponse);
  rpc getLiveNodes(LiveNodesRequest) returns (stream NodeInfoMessage);
}

message HeartbeatRequest {
  int64 nodeId = 1;
  string password = 2;
}

message HeartbeatResponse {
  bool success = 1;
}

message NodeInfoMessage {
  string address = 1;
  int32 udpPort = 2;
  int32 httpPort = 3;
  int32 grpcPort = 4;
  optional int32 configPort = 5;
  string prefix = 6;
}

message SubscribeRequest {
  NodeInfoMessage info = 1;
  string password = 2;
}

message SubscribeResponse{
  bool success = 1;
  int64 nodeId = 2;
}

message LiveNodesRequest {
  int64 nodeId = 1;
  string password = 2;
}