syntax = "proto3";
import "google/protobuf/empty.proto";

package node_b;
option java_package = "br.ufrn.dimap.grpc";
option java_multiple_files = true;

service MasterBankService {
  rpc createAccount(CreateAccountRequest) returns (AccountResponseWithSuccess);
  rpc withdraw(TransactionRequest) returns (AccountResponseWithSuccess);
  rpc deposit(TransactionRequest) returns (AccountResponseWithSuccess);
  rpc getAccount(BalanceRequest) returns (AccountResponseWithSuccess);
  rpc getAllAccounts(google.protobuf.Empty) returns (stream AccountResponse);
}

message CreateAccountRequest {
  string name = 1;
  int64 accountNumber = 2;
}

message AccountResponse {
  string name = 1;
  int64 accountNumber = 2;
  double balance = 3;
}

message BalanceRequest {
  int64 accountNumber = 1;
}

message TransactionRequest {
  int64 accountNumber = 2;
  double amount = 3;
}

message AccountResponseWithSuccess {
  AccountResponse account = 1;
  bool success = 2;
}